---
- hosts: all
  tasks:
    - name: Clean document root
      command: "rm -rf /var/www/vhosts/pmclain.com/*"

    - name: Unarchive artifact
      unarchive:
        src: "{{ lookup('env','WORKSPACE') }}/_site/build.tar.gz"
        dest: /var/www/vhosts/pmclain.com

    - name: Fix permissions
      file:
        path: /var/www/vhosts/pmclain.com
        state: directory
        recurse: yes
        owner: nginx
        group: nginx
